/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type Aid = number;
export declare type Bar = boolean;
export declare type Bfcache = boolean | null;
export declare type Cid = string;
export declare type Cmpid = string;
export declare type Cmsaid = string;
export declare type Csstatus = boolean | null;
export declare type Ebid = string;
export declare type Ets = string;
export declare type Evid = string;
export declare type Ht = string;
export declare type Ids1 = string;
export declare type Ids = Ids1[];
export declare type Kh = boolean;
export declare type Lis = boolean;
export declare type LoadRecomSrc1 = string;
export declare type LoadRecomSrc = LoadRecomSrc1[];
export declare type Nt = string;
export declare type ServerGuid = string;
export declare type Skid = number;
export declare type Ssoid = string;
export declare type St = string;
export declare type Url = string;
export interface ArtikelInview {
    [k: string]: unknown;
}
/**
 * This interface was referenced by `ArtikelInview`'s JSON-Schema
 * via the `definition` "ArtikelInviewSchema".
 */
export interface ArtikelInviewSchema {
    aid: Aid;
    bar?: Bar;
    bfcache?: Bfcache;
    cid?: Cid;
    cmpid?: Cmpid;
    cmsaid?: Cmsaid;
    csstatus?: Csstatus;
    ebid?: Ebid;
    ets?: Ets;
    evid?: Evid;
    ht: Ht;
    ids?: Ids;
    kh?: Kh;
    lis?: Lis;
    load_recom_src?: LoadRecomSrc;
    nt?: Nt;
    server_guid?: ServerGuid;
    skid?: Skid;
    ssoid?: Ssoid;
    st?: St;
    url: Url;
}
