/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Aid = number;
export type Bar = boolean;
export type Bfcache = boolean | null;
export type Cid = string;
export type Cids1 = string;
export type Cids = Cids1[];
export type Cmpid = string;
export type Cmsaid = string;
export type Csstatus = boolean | null;
export type Ebid = string;
export type Ets = string;
export type Evid = string;
export type Ht = string;
export type Kh = boolean;
export type Lis = boolean;
export type Ln = string;
export type LoadRecomSrc1 = string;
export type LoadRecomSrc = LoadRecomSrc1[];
export type Nt = string;
export type RecomSrc = string;
export type ServerGuid = string;
export type Skid = number;
export type Ssoid = string;
export type St = string;
export type Url = string;

export interface Contentinview {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Contentinview`'s JSON-Schema
 * via the `definition` "ContentInviewSchema".
 */
export interface ContentInviewSchema {
  aid: Aid;
  bar?: Bar;
  bfcache?: Bfcache;
  cid?: Cid;
  cids?: Cids;
  cmpid?: Cmpid;
  cmsaid?: Cmsaid;
  csstatus?: Csstatus;
  ebid?: Ebid;
  ets?: Ets;
  evid?: Evid;
  ht: Ht;
  kh?: Kh;
  lis?: Lis;
  ln?: Ln;
  load_recom_src?: LoadRecomSrc;
  nt?: Nt;
  recom_src?: RecomSrc;
  server_guid?: ServerGuid;
  skid?: Skid;
  ssoid?: Ssoid;
  st?: St;
  url: Url;
}
