/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Aid = number;
export type Areaid = string;
export type Articleid = string;
export type Articleurl = string;
export type Bar = boolean;
export type Bfcache = boolean | null;
export type Cid = string;
export type Cmpid = string;
export type Cmsaid = string;
export type Csstatus = boolean | null;
export type Deckid = string;
export type Ebid = string;
export type Editionid = string;
export type Ets = string;
export type Evid = string;
export type Ht = string;
export type Kh = boolean;
export type Lis = boolean;
export type Nt = string;
export type Productid = string;
export type ServerGuid = string;
export type Skid = number;
export type Ssoid = string;
export type St = string;
export type Url = string;

export interface Dreclick {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Dreclick`'s JSON-Schema
 * via the `definition` "DrEditionClickSchema".
 */
export interface DrEditionClickSchema {
  aid: Aid;
  areaid?: Areaid;
  articleid?: Articleid;
  articleurl?: Articleurl;
  bar?: Bar;
  bfcache?: Bfcache;
  cid?: Cid;
  cmpid?: Cmpid;
  cmsaid?: Cmsaid;
  csstatus?: Csstatus;
  deckid?: Deckid;
  ebid?: Ebid;
  editionid?: Editionid;
  ets?: Ets;
  evid?: Evid;
  ht: Ht;
  kh?: Kh;
  lis?: Lis;
  nt?: Nt;
  productid?: Productid;
  server_guid?: ServerGuid;
  skid?: Skid;
  ssoid?: Ssoid;
  st?: St;
  url: Url;
}
