/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type Aid = number;
export declare type Bar = boolean;
export declare type Bfcache = boolean | null;
export declare type Cid = string;
export declare type Cmpid = string;
export declare type Cmsaid = string;
export declare type Csstatus = boolean | null;
export declare type Ebid = string;
export declare type El1 = string;
export declare type El2 = string;
export declare type El3 = string;
export declare type El4 = string;
export declare type Ets = string;
export declare type Evid = string;
export declare type Ht = string;
export declare type Kh = boolean;
export declare type Lis = boolean;
export declare type Nt = string;
export declare type Pfs = string;
export declare type ServerGuid = string;
export declare type Skid = number;
export declare type Ssoid = string;
export declare type St = string;
export declare type Url = string;
export interface Event {
    [k: string]: unknown;
}
/**
 * This interface was referenced by `Event`'s JSON-Schema
 * via the `definition` "EventSchema".
 */
export interface EventSchema {
    aid: Aid;
    bar?: Bar;
    bfcache?: Bfcache;
    cid?: Cid;
    cmpid?: Cmpid;
    cmsaid?: Cmsaid;
    csstatus?: Csstatus;
    ebid?: Ebid;
    el1?: El1;
    el2?: El2;
    el3?: El3;
    el4?: El4;
    ets?: Ets;
    evid?: Evid;
    ht: Ht;
    kh?: Kh;
    lis?: Lis;
    nt?: Nt;
    pfs?: Pfs;
    server_guid?: ServerGuid;
    skid?: Skid;
    ssoid?: Ssoid;
    st?: St;
    url: Url;
}
