/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type Aid = number;
export declare type Bar = boolean;
export declare type Bfcache = boolean | null;
export declare type Cid = string;
export declare type Cmpid = string;
export declare type Csstatus = boolean | null;
export declare type Ebid = string;
export declare type Ets = string;
export declare type Evid = string;
export declare type Geo = string;
export declare type Ht = string;
export declare type Kh = boolean;
export declare type Lis = boolean;
export declare type Miteb1 = string;
export declare type Nt = string;
export declare type ServerGuid = string;
export declare type Skid = number;
export declare type Ssoid = string;
export declare type St = string;
export declare type Tagname = string;
export declare type Url = string;
export interface Miteb {
    [k: string]: unknown;
}
/**
 * This interface was referenced by `Miteb`'s JSON-Schema
 * via the `definition` "MitEbSchema".
 */
export interface MitEbSchema {
    aid: Aid;
    bar?: Bar;
    bfcache?: Bfcache;
    cid?: Cid;
    cmpid?: Cmpid;
    csstatus?: Csstatus;
    ebid?: Ebid;
    ets?: Ets;
    evid?: Evid;
    geo?: Geo;
    ht: Ht;
    kh?: Kh;
    lis?: Lis;
    miteb?: Miteb1;
    nt?: Nt;
    server_guid?: ServerGuid;
    skid?: Skid;
    ssoid?: Ssoid;
    st?: St;
    tagname?: Tagname;
    url: Url;
}
