/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type Aid = number;
export declare type At = string;
export declare type Bar = boolean;
export declare type Bfcache = boolean | null;
export declare type Cid = string;
export declare type Cmpid = string;
export declare type Csstatus = boolean | null;
export declare type Ebid = string;
export declare type Ekid = string;
export declare type Ets = string;
export declare type Evid = string;
export declare type Geo = string;
export declare type Ht = string;
export declare type Ikid = string;
export declare type Ipad = boolean | null;
export declare type Kh = boolean;
export declare type La = boolean;
export declare type Lis = boolean;
export declare type Lsicid = string;
export declare type Nt = string;
export declare type Pfs = string;
export declare type Ref = string;
export declare type ServerGuid = string;
export declare type Skid = number;
export declare type Ssoid = string;
export declare type St = string;
export declare type Url = string;
export interface Pageview {
    [k: string]: unknown;
}
/**
 * This interface was referenced by `Pageview`'s JSON-Schema
 * via the `definition` "PageviewSchema".
 */
export interface PageviewSchema {
    aid: Aid;
    at?: At;
    bar?: Bar;
    bfcache?: Bfcache;
    cid?: Cid;
    cmpid?: Cmpid;
    csstatus?: Csstatus;
    ebid?: Ebid;
    ekid?: Ekid;
    ets?: Ets;
    evid?: Evid;
    geo?: Geo;
    ht: Ht;
    ikid?: Ikid;
    ipad?: Ipad;
    kh?: Kh;
    la?: La;
    lis?: Lis;
    lsicid?: Lsicid;
    nt?: Nt;
    pfs?: Pfs;
    ref?: Ref;
    server_guid?: ServerGuid;
    skid?: Skid;
    ssoid?: Ssoid;
    st?: St;
    url: Url;
}
