/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type Aid = number;
export declare type Bar = boolean;
export declare type Bfcache = boolean | null;
export declare type Cid = string;
export declare type Cmpid = string;
export declare type Csstatus = boolean | null;
export declare type Ebid = string;
export declare type Ets = string;
export declare type Evid = string;
export declare type Ht = string;
export declare type Kh = boolean;
export declare type Lis = boolean;
export declare type Nt = string;
export declare type ServerGuid = string;
export declare type Skid = number;
export declare type Ssoid = string;
export declare type St = string;
export declare type Url = string;
export declare type Vctx = string;
export declare type Vet = string;
export declare type Vidap = boolean;
export declare type Vidban = boolean;
export declare type Vidbanop = string;
export declare type Vidcp = string;
export declare type Viddcid = string;
export declare type Videid = string;
export declare type Viden = string;
export declare type Videvtd = string;
export declare type Videvtl = string;
export declare type Vidid = string;
export declare type Vidpid = string;
export declare type Vidpn = string;
export declare type Vidtype = string;
export interface Video {
    [k: string]: unknown;
}
/**
 * This interface was referenced by `Video`'s JSON-Schema
 * via the `definition` "VideoSchema".
 */
export interface VideoSchema {
    aid: Aid;
    bar?: Bar;
    bfcache?: Bfcache;
    cid?: Cid;
    cmpid?: Cmpid;
    csstatus?: Csstatus;
    ebid?: Ebid;
    ets?: Ets;
    evid?: Evid;
    ht: Ht;
    kh?: Kh;
    lis?: Lis;
    nt?: Nt;
    server_guid?: ServerGuid;
    skid?: Skid;
    ssoid?: Ssoid;
    st?: St;
    url: Url;
    vctx?: Vctx;
    vet?: Vet;
    vidap?: Vidap;
    vidban?: Vidban;
    vidbanop?: Vidbanop;
    vidcp?: Vidcp;
    viddcid?: Viddcid;
    videid?: Videid;
    viden?: Viden;
    videvtd?: Videvtd;
    videvtl?: Videvtl;
    vidid?: Vidid;
    vidpid?: Vidpid;
    vidpn?: Vidpn;
    vidtype?: Vidtype;
}
