/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Aid = number;
export type Bar = boolean;
export type Bfcache = boolean | null;
export type Cid = string;
export type Cmpid = string;
export type Csstatus = boolean | null;
export type Ebid = string;
export type Ets = string;
export type Evid = string;
export type Ht = string;
export type Kh = boolean;
export type Lis = boolean;
export type Nt = string;
export type ServerGuid = string;
export type Skid = number;
export type Ssoid = string;
export type St = string;
export type Url = string;
export type Vctx = string;
export type Vet = string;
export type Vidap = boolean;
export type Vidban = boolean;
export type Vidbanop = string;
export type Vidcp = string;
export type Viddcid = string;
export type Videid = string;
export type Viden = string;
export type Videvtd = string;
export type Videvtl = string;
export type Vidid = string;
export type Vidpid = string;
export type Vidpn = string;
export type Vidtype = string;

export interface Video {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Video`'s JSON-Schema
 * via the `definition` "VideoSchema".
 */
export interface VideoSchema {
  aid: Aid;
  bar?: Bar;
  bfcache?: Bfcache;
  cid?: Cid;
  cmpid?: Cmpid;
  csstatus?: Csstatus;
  ebid?: Ebid;
  ets?: Ets;
  evid?: Evid;
  ht: Ht;
  kh?: Kh;
  lis?: Lis;
  nt?: Nt;
  server_guid?: ServerGuid;
  skid?: Skid;
  ssoid?: Ssoid;
  st?: St;
  url: Url;
  vctx?: Vctx;
  vet?: Vet;
  vidap?: Vidap;
  vidban?: Vidban;
  vidbanop?: Vidbanop;
  vidcp?: Vidcp;
  viddcid?: Viddcid;
  videid?: Videid;
  viden?: Viden;
  videvtd?: Videvtd;
  videvtl?: Videvtl;
  vidid?: Vidid;
  vidpid?: Vidpid;
  vidpn?: Vidpn;
  vidtype?: Vidtype;
}
